version: "3.8"

services:
  # mongodb:
  #   container_name: mongodb
  #   image: mongo:latest
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb-data:/data/db

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
  #   container_name: elasticsearch
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es
  #     - bootstrap.memory_lock=true
  #     - ES_JAVA_OPTS=-Xms2g -Xmx2g
  #     - xpack.security.enabled=false
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #     - 9300:9300

  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:7.13.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox
      - MYSQL_DATABASE=veritrade-test
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    ports:
      - 8082:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=sandbox
      - PMA_PASSWORD=sandbox
    depends_on:
      - mysql

  cache:
    image: redis
    container_name: cache
    ports:
      - 6379:6379
    volumes:
      - cache-data:/data

volumes:
  mongodb-data:
    driver: local
  mysql-data:
    driver: local
  cache-data:
    driver: local
