version: "3.3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: boilerplate
      MYSQL_USER: sandbox
      MYSQL_ROOT_PASSWORD: sandbox
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
