const data = [
  {
    id: 'AF',
    name_es: 'Afganistán',
    name_en: 'Afghanistan',
    dial_code: '93',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AFN',
  },
  {
    id: 'AX',
    name_es: 'Islas Aland',
    name_en: 'Aland Islands',
    dial_code: '358',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'AL',
    name_es: 'Albania',
    name_en: 'Albania',
    dial_code: '355',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ALL',
  },
  {
    id: 'DZ',
    name_es: 'Argelia',
    name_en: 'Algeria',
    dial_code: '213',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'DZD',
  },
  {
    id: 'AS',
    name_es: 'Samoa Americana',
    name_en: 'American Samoa',
    dial_code: '1684',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'AD',
    name_es: 'Andorra',
    name_en: 'Andorra',
    dial_code: '376',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'AO',
    name_es: 'Angola',
    name_en: 'Angola',
    dial_code: '244',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AOA',
  },
  {
    id: 'AI',
    name_es: 'Anguila',
    name_en: 'Anguilla',
    dial_code: '1264',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XCD',
  },
  {
    id: 'AQ',
    name_es: 'Antártida',
    name_en: 'Antarctica',
    dial_code: '672',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'AG',
    name_es: 'Antigua y Barbuda',
    name_en: 'Antigua and Barbuda',
    dial_code: '1268',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XCD',
  },
  {
    id: 'AR',
    name_es: 'Argentina',
    name_en: 'Argentina',
    dial_code: '54',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'ARS',
  },
  {
    id: 'AM',
    name_es: 'Armenia',
    name_en: 'Armenia',
    dial_code: '374',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AMD',
  },
  {
    id: 'AW',
    name_es: 'Aruba',
    name_en: 'Aruba',
    dial_code: '297',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AWG',
  },
  {
    id: 'AU',
    name_es: 'Australia',
    name_en: 'Australia',
    dial_code: '61',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AUD',
  },
  {
    id: 'AT',
    name_es: 'Austria',
    name_en: 'Austria',
    dial_code: '43',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'AZ',
    name_es: 'Azerbaiyán',
    name_en: 'Azerbaijan',
    dial_code: '994',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AZN',
  },
  {
    id: 'BS',
    name_es: 'Bahamas',
    name_en: 'Bahamas',
    dial_code: '1242',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BSD',
  },
  {
    id: 'BH',
    name_es: 'Bahrein',
    name_en: 'Bahrain',
    dial_code: '973',
    paypal_accepted: '1',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'BHD',
  },
  {
    id: 'BD',
    name_es: 'Bangladesh',
    name_en: 'Bangladesh',
    dial_code: '880',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BDT',
  },
  {
    id: 'BB',
    name_es: 'Barbados',
    name_en: 'Barbados',
    dial_code: '1246',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BBD',
  },
  {
    id: 'BY',
    name_es: 'Bielorrusia',
    name_en: 'Belarus',
    dial_code: '375',
    paypal_accepted: '1',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'BYR',
  },
  {
    id: 'BE',
    name_es: 'Bélgica',
    name_en: 'Belgium',
    dial_code: '32',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'BZ',
    name_es: 'Belice',
    name_en: 'Belize',
    dial_code: '501',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BZD',
  },
  {
    id: 'BJ',
    name_es: 'Benin',
    name_en: 'Benin',
    dial_code: '229',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XOF',
  },
  {
    id: 'BM',
    name_es: 'Islas Bermudas',
    name_en: 'Bermuda',
    dial_code: '1441',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BMD',
  },
  {
    id: 'BT',
    name_es: 'Bután',
    name_en: 'Bhutan',
    dial_code: '975',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BTN',
  },
  {
    id: 'BO',
    name_es: 'Bolivia',
    name_en: 'Bolivia',
    dial_code: '591',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'BOB',
  },
  {
    id: 'BA',
    name_es: 'Bosnia y Herzegovina',
    name_en: 'Bosnia and Herzegovina',
    dial_code: '387',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BAM',
  },
  {
    id: 'BW',
    name_es: 'Botsuana',
    name_en: 'Botswana',
    dial_code: '267',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BWP',
  },
  {
    id: 'BV',
    name_es: 'Isla Bouvet',
    name_en: 'Bouvet Island',
    dial_code: '47',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NOK',
  },
  {
    id: 'BR',
    name_es: 'Brasil',
    name_en: 'Brazil',
    dial_code: '55',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BRL',
  },
  {
    id: 'IO',
    name_es: 'Territorio Británico del Océano Índico',
    name_en: 'British Indian Ocean Territory',
    dial_code: '246',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'BN',
    name_es: 'Brunei Darussalam',
    name_en: 'Brunei Darussalam',
    dial_code: '673',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BND',
  },
  {
    id: 'BG',
    name_es: 'Bulgaria',
    name_en: 'Bulgaria',
    dial_code: '359',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BGN',
  },
  {
    id: 'BF',
    name_es: 'Burkina Faso',
    name_en: 'Burkina Faso',
    dial_code: '226',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XOF',
  },
  {
    id: 'BI',
    name_es: 'Burundi',
    name_en: 'Burundi',
    dial_code: '257',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'BIF',
  },
  {
    id: 'KH',
    name_es: 'Camboya',
    name_en: 'Cambodia',
    dial_code: '855',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'KHR',
  },
  {
    id: 'CM',
    name_es: 'Camerún',
    name_en: 'Cameroon',
    dial_code: '237',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XAF',
  },
  {
    id: 'CA',
    name_es: 'Canadá',
    name_en: 'Canada',
    dial_code: '1',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'CAD',
  },
  {
    id: 'CV',
    name_es: 'Cabo Verde',
    name_en: 'Cape Verde',
    dial_code: '238',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'CVE',
  },
  {
    id: 'KY',
    name_es: 'Islas Caimán',
    name_en: 'Cayman Islands',
    dial_code: '1345',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'KYD',
  },
  {
    id: 'CF',
    name_es: 'República Centroafricana',
    name_en: 'Central African Republic',
    dial_code: '236',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XAF',
  },
  {
    id: 'TD',
    name_es: 'Chad',
    name_en: 'Chad',
    dial_code: '235',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XAF',
  },
  {
    id: 'CL',
    name_es: 'Chile',
    name_en: 'Chile',
    dial_code: '56',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'CLP',
  },
  {
    id: 'CN',
    name_es: 'China',
    name_en: 'China',
    dial_code: '86',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'CNY',
  },
  {
    id: 'CX',
    name_es: 'Isla de Navidad',
    name_en: 'Christmas Island',
    dial_code: '61',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AUD',
  },
  {
    id: 'CO',
    name_es: 'Colombia',
    name_en: 'Colombia',
    dial_code: '57',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'COP',
  },
  {
    id: 'KM',
    name_es: 'Comoras',
    name_en: 'Comoros',
    dial_code: '269',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'KMF',
  },
  {
    id: 'CG',
    name_es: 'Congo',
    name_en: 'Congo',
    dial_code: '242',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XAF',
  },
  {
    id: 'CK',
    name_es: 'Islas Cook',
    name_en: 'Cook Islands',
    dial_code: '682',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NZD',
  },
  {
    id: 'CR',
    name_es: 'Costa Rica',
    name_en: 'Costa Rica',
    dial_code: '506',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'CRC',
  },
  {
    id: 'HR',
    name_es: 'Croacia',
    name_en: 'Croatia',
    dial_code: '385',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'HRK',
  },
  {
    id: 'CU',
    name_es: 'Cuba',
    name_en: 'Cuba',
    dial_code: '53',
    paypal_accepted: '0',
    cards_accepted: '0',
    locale_id: 'es',
    currency_id: 'CUC',
  },
  {
    id: 'CW',
    name_es: 'Curazao',
    name_en: 'Curaçao',
    dial_code: '599',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ANG',
  },
  {
    id: 'CY',
    name_es: 'Chipre',
    name_en: 'Cyprus',
    dial_code: '357',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'CZ',
    name_es: 'República Checa',
    name_en: 'Czech Republic',
    dial_code: '420',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'CZK',
  },
  {
    id: 'CD',
    name_es: 'República Democrática del Congo',
    name_en: 'Democratic Republic of the Congo',
    dial_code: '243',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'CDF',
  },
  {
    id: 'DK',
    name_es: 'Dinamarca',
    name_en: 'Denmark',
    dial_code: '45',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'DKK',
  },
  {
    id: 'DJ',
    name_es: 'Djibouti',
    name_en: 'Djibouti',
    dial_code: '253',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'DJF',
  },
  {
    id: 'DM',
    name_es: 'Dominica',
    name_en: 'Dominica',
    dial_code: '767',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XCD',
  },
  {
    id: 'DO',
    name_es: 'República Dominicana',
    name_en: 'Dominican Republic',
    dial_code: '809',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'DOP',
  },
  {
    id: 'TL',
    name_es: 'Timor Oriental',
    name_en: 'East Timor',
    dial_code: '670',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'EC',
    name_es: 'Ecuador',
    name_en: 'Ecuador',
    dial_code: '593',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'USD',
  },
  {
    id: 'EG',
    name_es: 'Egipto',
    name_en: 'Egypt',
    dial_code: '20',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EGP',
  },
  {
    id: 'SV',
    name_es: 'El Salvador',
    name_en: 'El Salvador',
    dial_code: '503',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'USD',
  },
  {
    id: 'GB-ENG',
    name_es: 'Inglaterra',
    name_en: 'England',
    dial_code: '44',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GBP',
  },
  {
    id: 'GQ',
    name_es: 'Guinea Ecuatorial',
    name_en: 'Equatorial Guinea',
    dial_code: '240',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'XAF',
  },
  {
    id: 'ER',
    name_es: 'Eritrea',
    name_en: 'Eritrea',
    dial_code: '291',
    paypal_accepted: '1',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'ERN',
  },
  {
    id: 'EE',
    name_es: 'Estonia',
    name_en: 'Estonia',
    dial_code: '372',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'ET',
    name_es: 'Etiopía',
    name_en: 'Ethiopia',
    dial_code: '251',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ETB',
  },
  {
    id: 'FK',
    name_es: 'Islas Malvinas',
    name_en: 'Falkland Islands',
    dial_code: '500',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'FKP',
  },
  {
    id: 'FO',
    name_es: 'Islas Faroe',
    name_en: 'Faroe Islands',
    dial_code: '298',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'DKK',
  },
  {
    id: 'FJ',
    name_es: 'Fiyi',
    name_en: 'Fiji',
    dial_code: '679',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'FJD',
  },
  {
    id: 'FI',
    name_es: 'Finlandia',
    name_en: 'Finland',
    dial_code: '358',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'FR',
    name_es: 'Francia',
    name_en: 'France',
    dial_code: '33',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'GF',
    name_es: 'Guayana Francesa',
    name_en: 'French Guiana',
    dial_code: '594',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'PF',
    name_es: 'Polinesia francés',
    name_en: 'French Polynesia',
    dial_code: '689',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XPF',
  },
  {
    id: 'TF',
    name_es: 'Tierras australes y antárticas francesas',
    name_en: 'French Southern and Antarctic Lands',
    dial_code: '262',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'GA',
    name_es: 'Gabón',
    name_en: 'Gabon',
    dial_code: '241',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XAF',
  },
  {
    id: 'GM',
    name_es: 'Gambia',
    name_en: 'Gambia',
    dial_code: '220',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GMD',
  },
  {
    id: 'GE',
    name_es: 'Georgia',
    name_en: 'Georgia',
    dial_code: '995',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GEL',
  },
  {
    id: 'DE',
    name_es: 'Alemania',
    name_en: 'Germany',
    dial_code: '49',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'GH',
    name_es: 'Ghana',
    name_en: 'Ghana',
    dial_code: '233',
    paypal_accepted: '0',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'GHS',
  },
  {
    id: 'GI',
    name_es: 'Gibraltar',
    name_en: 'Gibraltar',
    dial_code: '350',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GIP',
  },
  {
    id: 'GR',
    name_es: 'Grecia',
    name_en: 'Greece',
    dial_code: '30',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'GL',
    name_es: 'Groenlandia',
    name_en: 'Greenland',
    dial_code: '299',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'DKK',
  },
  {
    id: 'GD',
    name_es: 'Granada',
    name_en: 'Grenada',
    dial_code: '1473',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XCD',
  },
  {
    id: 'GP',
    name_es: 'Guadalupe',
    name_en: 'Guadeloupe',
    dial_code: '590',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'GU',
    name_es: 'Guam',
    name_en: 'Guam',
    dial_code: '1',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'GT',
    name_es: 'Guatemala',
    name_en: 'Guatemala',
    dial_code: '502',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'GTQ',
  },
  {
    id: 'GG',
    name_es: 'Guernsey',
    name_en: 'Guernsey',
    dial_code: '44',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GGP',
  },
  {
    id: 'GN',
    name_es: 'Guinea',
    name_en: 'Guinea',
    dial_code: '224',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GNF',
  },
  {
    id: 'GW',
    name_es: 'Guinea-Bissau',
    name_en: 'Guinea-Bissau',
    dial_code: '245',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XOF',
  },
  {
    id: 'GY',
    name_es: 'Guayana',
    name_en: 'Guyana',
    dial_code: '592',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GYD',
  },
  {
    id: 'HT',
    name_es: 'Haití',
    name_en: 'Haiti',
    dial_code: '509',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'HTG',
  },
  {
    id: 'HM',
    name_es: 'Islas Heard y McDonald',
    name_en: 'Heard Island and McDonald Islands',
    dial_code: '672',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AUD',
  },
  {
    id: 'HN',
    name_es: 'Honduras',
    name_en: 'Honduras',
    dial_code: '504',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'HNL',
  },
  {
    id: 'HK',
    name_es: 'Hong Kong',
    name_en: 'Hong Kong',
    dial_code: '852',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'HKD',
  },
  {
    id: 'HU',
    name_es: 'Hungría',
    name_en: 'Hungary',
    dial_code: '36',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'HUF',
  },
  {
    id: 'IS',
    name_es: 'Islandia',
    name_en: 'Iceland',
    dial_code: '354',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ISK',
  },
  {
    id: 'IN',
    name_es: 'India',
    name_en: 'India',
    dial_code: '91',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'INR',
  },
  {
    id: 'ID',
    name_es: 'Indonesia',
    name_en: 'Indonesia',
    dial_code: '62',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'IDR',
  },
  {
    id: 'IR',
    name_es: 'Irán',
    name_en: 'Iran',
    dial_code: '98',
    paypal_accepted: '0',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'IRR',
  },
  {
    id: 'IQ',
    name_es: 'Irak',
    name_en: 'Iraq',
    dial_code: '964',
    paypal_accepted: '0',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'IQD',
  },
  {
    id: 'IE',
    name_es: 'Irlanda',
    name_en: 'Ireland',
    dial_code: '353',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'IM',
    name_es: 'Isla de Man',
    name_en: 'Isle of Man',
    dial_code: '44',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'IMP',
  },
  {
    id: 'IL',
    name_es: 'Israel',
    name_en: 'Israel',
    dial_code: '972',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ILS',
  },
  {
    id: 'IT',
    name_es: 'Italia',
    name_en: 'Italy',
    dial_code: '39',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'CI',
    name_es: 'Costa de Marfil',
    name_en: 'Ivory Coast',
    dial_code: '225',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XOF',
  },
  {
    id: 'JM',
    name_es: 'Jamaica',
    name_en: 'Jamaica',
    dial_code: '876',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'JMD',
  },
  {
    id: 'JP',
    name_es: 'Japón',
    name_en: 'Japan',
    dial_code: '81',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'JPY',
  },
  {
    id: 'JE',
    name_es: 'Jersey',
    name_en: 'Jersey',
    dial_code: '44',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'JEP',
  },
  {
    id: 'JO',
    name_es: 'Jordán',
    name_en: 'Jordan',
    dial_code: '962',
    paypal_accepted: '1',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'JOD',
  },
  {
    id: 'KZ',
    name_es: 'Kazajstán',
    name_en: 'Kazakhstan',
    dial_code: '7',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'KZT',
  },
  {
    id: 'CC',
    name_es: 'Islas Keeling',
    name_en: 'Keeling Islands',
    dial_code: '61',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AUD',
  },
  {
    id: 'KE',
    name_es: 'Kenia',
    name_en: 'Kenya',
    dial_code: '254',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'KES',
  },
  {
    id: 'KI',
    name_es: 'Kiribati',
    name_en: 'Kiribati',
    dial_code: '686',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AUD',
  },
  {
    id: 'KW',
    name_es: 'Kuwait',
    name_en: 'Kuwait',
    dial_code: '965',
    paypal_accepted: '1',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'KWD',
  },
  {
    id: 'KG',
    name_es: 'Kirguistán',
    name_en: 'Kyrgyzstan',
    dial_code: '996',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'KGS',
  },
  {
    id: 'LA',
    name_es: 'Laos',
    name_en: 'Laos',
    dial_code: '856',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'LAK',
  },
  {
    id: 'LV',
    name_es: 'Letonia',
    name_en: 'Latvia',
    dial_code: '371',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'LB',
    name_es: 'Líbano',
    name_en: 'Lebanon',
    dial_code: '961',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'LBP',
  },
  {
    id: 'LS',
    name_es: 'Lesoto',
    name_en: 'Lesotho',
    dial_code: '266',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'LSL',
  },
  {
    id: 'LR',
    name_es: 'Liberia',
    name_en: 'Liberia',
    dial_code: '231',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'LRD',
  },
  {
    id: 'LY',
    name_es: 'Libia',
    name_en: 'Libya',
    dial_code: '218',
    paypal_accepted: '0',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'LYD',
  },
  {
    id: 'LI',
    name_es: 'Liechtenstein',
    name_en: 'Liechtenstein',
    dial_code: '423',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'CHF',
  },
  {
    id: 'LT',
    name_es: 'Lituania',
    name_en: 'Lithuania',
    dial_code: '370',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'LU',
    name_es: 'Luxemburgo',
    name_en: 'Luxembourg',
    dial_code: '352',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'MO',
    name_es: 'Macao',
    name_en: 'Macao',
    dial_code: '853',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MOP',
  },
  {
    id: 'MK',
    name_es: 'Macedonia',
    name_en: 'Macedonia',
    dial_code: '389',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MKD',
  },
  {
    id: 'MG',
    name_es: 'Madagascar',
    name_en: 'Madagascar',
    dial_code: '261',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MGA',
  },
  {
    id: 'MW',
    name_es: 'Malawi',
    name_en: 'Malawi',
    dial_code: '265',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MWK',
  },
  {
    id: 'MY',
    name_es: 'Malasia',
    name_en: 'Malaysia',
    dial_code: '60',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MYR',
  },
  {
    id: 'MV',
    name_es: 'Maldivas',
    name_en: 'Maldives',
    dial_code: '960',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MVR',
  },
  {
    id: 'ML',
    name_es: 'Mali',
    name_en: 'Mali',
    dial_code: '223',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XOF',
  },
  {
    id: 'MT',
    name_es: 'Malta',
    name_en: 'Malta',
    dial_code: '356',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'MH',
    name_es: 'Islas Marshall',
    name_en: 'Marshall Islands',
    dial_code: '692',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'MQ',
    name_es: 'Martinica',
    name_en: 'Martinique',
    dial_code: '596',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'MR',
    name_es: 'Mauritania',
    name_en: 'Mauritania',
    dial_code: '222',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MRU',
  },
  {
    id: 'MU',
    name_es: 'Mauricio',
    name_en: 'Mauritius',
    dial_code: '230',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MUR',
  },
  {
    id: 'YT',
    name_es: 'Mayotte',
    name_en: 'Mayotte',
    dial_code: '262',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'MX',
    name_es: 'México',
    name_en: 'Mexico',
    dial_code: '52',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'MXN',
  },
  {
    id: 'FM',
    name_es: 'Micronesia',
    name_en: 'Micronesia',
    dial_code: '691',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'MD',
    name_es: 'Moldavia',
    name_en: 'Moldova',
    dial_code: '373',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MDL',
  },
  {
    id: 'MC',
    name_es: 'Mónaco',
    name_en: 'Monaco',
    dial_code: '377',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'MN',
    name_es: 'Mongolia',
    name_en: 'Mongolia',
    dial_code: '976',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MNT',
  },
  {
    id: 'ME',
    name_es: 'Montenegro',
    name_en: 'Montenegro',
    dial_code: '382',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'MS',
    name_es: 'Montserrat',
    name_en: 'Montserrat',
    dial_code: '1664',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XCD',
  },
  {
    id: 'MA',
    name_es: 'Marruecos',
    name_en: 'Morocco',
    dial_code: '212',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MAD',
  },
  {
    id: 'MZ',
    name_es: 'Mozambique',
    name_en: 'Mozambique',
    dial_code: '258',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MZN',
  },
  {
    id: 'MM',
    name_es: 'Myanmar',
    name_en: 'Myanmar',
    dial_code: '95',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'MMK',
  },
  {
    id: 'NA',
    name_es: 'Namibia',
    name_en: 'Namibia',
    dial_code: '264',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NAD',
  },
  {
    id: 'NR',
    name_es: 'Nauru',
    name_en: 'Nauru',
    dial_code: '674',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AUD',
  },
  {
    id: 'NP',
    name_es: 'Nepal',
    name_en: 'Nepal',
    dial_code: '977',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NPR',
  },
  {
    id: 'NL',
    name_es: 'Países Bajos',
    name_en: 'Netherlands',
    dial_code: '31',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'NC',
    name_es: 'Nueva Caledonia',
    name_en: 'New Caledonia',
    dial_code: '687',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XPF',
  },
  {
    id: 'NZ',
    name_es: 'Nueva Zelanda',
    name_en: 'New Zealand',
    dial_code: '64',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NZD',
  },
  {
    id: 'NI',
    name_es: 'Nicaragua',
    name_en: 'Nicaragua',
    dial_code: '505',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'NIO',
  },
  {
    id: 'NE',
    name_es: 'Níger',
    name_en: 'Niger',
    dial_code: '227',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XOF',
  },
  {
    id: 'NG',
    name_es: 'Nigeria',
    name_en: 'Nigeria',
    dial_code: '234',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NGN',
  },
  {
    id: 'NU',
    name_es: 'Niue',
    name_en: 'Niue',
    dial_code: '683',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NZD',
  },
  {
    id: 'NF',
    name_es: 'Isla Norfolk',
    name_en: 'Norfolk Island',
    dial_code: '672',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AUD',
  },
  {
    id: 'KP',
    name_es: 'Corea del Norte',
    name_en: 'North Korea',
    dial_code: '850',
    paypal_accepted: '0',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'KPW',
  },
  {
    id: 'GB-NIR',
    name_es: 'Irlanda del Norte',
    name_en: 'Northern Ireland',
    dial_code: '44',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GBP',
  },
  {
    id: 'MP',
    name_es: 'Islas Marianas del Norte',
    name_en: 'Northern Mariana Islands',
    dial_code: '1670',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'NO',
    name_es: 'Noruega',
    name_en: 'Norway',
    dial_code: '47',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NOK',
  },
  {
    id: 'OM',
    name_es: 'Omán',
    name_en: 'Oman',
    dial_code: '968',
    paypal_accepted: '1',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'OMR',
  },
  {
    id: 'PK',
    name_es: 'Pakistán',
    name_en: 'Pakistan',
    dial_code: '92',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'PKR',
  },
  {
    id: 'PW',
    name_es: 'Palau',
    name_en: 'Palau',
    dial_code: '680',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'PS',
    name_es: 'Palestina',
    name_en: 'Palestine',
    dial_code: '970',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ILS',
  },
  {
    id: 'PA',
    name_es: 'Panamá',
    name_en: 'Panama',
    dial_code: '507',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'USD',
  },
  {
    id: 'PG',
    name_es: 'Papúa Nueva Guinea',
    name_en: 'Papua New Guinea',
    dial_code: '675',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'PGK',
  },
  {
    id: 'PY',
    name_es: 'Paraguay',
    name_en: 'Paraguay',
    dial_code: '595',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'PYG',
  },
  {
    id: 'PE',
    name_es: 'Perú',
    name_en: 'Peru',
    dial_code: '51',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'PEN',
  },
  {
    id: 'PH',
    name_es: 'Filipinas',
    name_en: 'Philippines',
    dial_code: '63',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'PHP',
  },
  {
    id: 'PN',
    name_es: 'Islas Pitcairn',
    name_en: 'Pitcairn Islands',
    dial_code: '870',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NZD',
  },
  {
    id: 'PL',
    name_es: 'Polonia',
    name_en: 'Poland',
    dial_code: '48',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'PLN',
  },
  {
    id: 'PT',
    name_es: 'Portugal',
    name_en: 'Portugal',
    dial_code: '351',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'PR',
    name_es: 'Puerto Rico',
    name_en: 'Puerto Rico',
    dial_code: '1',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'QA',
    name_es: 'Katar',
    name_en: 'Qatar',
    dial_code: '974',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'QAR',
  },
  {
    id: 'RE',
    name_es: 'Reunión',
    name_en: 'Réunion',
    dial_code: '262',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'RO',
    name_es: 'Rumania',
    name_en: 'Romania',
    dial_code: '40',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'RON',
  },
  {
    id: 'RU',
    name_es: 'Rusia',
    name_en: 'Russia',
    dial_code: '7',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'RUB',
  },
  {
    id: 'RW',
    name_es: 'Ruanda',
    name_en: 'Rwanda',
    dial_code: '250',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'RWF',
  },
  {
    id: 'ST',
    name_es: 'Santo Tomé y Príncipe',
    name_en: 'São Tomé and Príncipe',
    dial_code: '239',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'STN',
  },
  {
    id: 'BL',
    name_es: 'San Bartolomé',
    name_en: 'Saint Barthélemy',
    dial_code: '590',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'KN',
    name_es: 'San Cristóbal y Nieves',
    name_en: 'Saint Kitts and Nevis',
    dial_code: '1869',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XCD',
  },
  {
    id: 'LC',
    name_es: 'Santa Lucía',
    name_en: 'Saint Lucia',
    dial_code: '1758',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XCD',
  },
  {
    id: 'PM',
    name_es: 'San Pedro y Miquelón',
    name_en: 'Saint Pierre and Miquelon',
    dial_code: '508',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'VC',
    name_es: 'San Vicente y las Granadinas',
    name_en: 'Saint Vincent and the Grenadines',
    dial_code: '1784',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XCD',
  },
  {
    id: 'WS',
    name_es: 'Samoa',
    name_en: 'Samoa',
    dial_code: '685',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'WST',
  },
  {
    id: 'SM',
    name_es: 'San Marino',
    name_en: 'San Marino',
    dial_code: '378',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'SA',
    name_es: 'Arabia Saudita',
    name_en: 'Saudi Arabia',
    dial_code: '966',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SAR',
  },
  {
    id: 'GB-SCT',
    name_es: 'Escocia',
    name_en: 'Scotland',
    dial_code: '44',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GBP',
  },
  {
    id: 'SN',
    name_es: 'Senegal',
    name_en: 'Senegal',
    dial_code: '221',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XOF',
  },
  {
    id: 'RS',
    name_es: 'Serbia',
    name_en: 'Serbia',
    dial_code: '381',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'RSD',
  },
  {
    id: 'SC',
    name_es: 'Seychelles',
    name_en: 'Seychelles',
    dial_code: '248',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SCR',
  },
  {
    id: 'SL',
    name_es: 'Sierra Leona',
    name_en: 'Sierra Leone',
    dial_code: '232',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SLL',
  },
  {
    id: 'SG',
    name_es: 'Singapur',
    name_en: 'Singapore',
    dial_code: '65',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SGD',
  },
  {
    id: 'SX',
    name_es: 'Sint Maarten',
    name_en: 'Sint Maarten',
    dial_code: '1721',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ANG',
  },
  {
    id: 'SK',
    name_es: 'Eslovaquia',
    name_en: 'Slovakia',
    dial_code: '421',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'SI',
    name_es: 'Eslovenia',
    name_en: 'Slovenia',
    dial_code: '386',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'SB',
    name_es: 'Islas Salomón',
    name_en: 'Solomon Islands',
    dial_code: '677',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SBD',
  },
  {
    id: 'SO',
    name_es: 'Somalia',
    name_en: 'Somalia',
    dial_code: '252',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SOS',
  },
  {
    id: 'ZA',
    name_es: 'Sudáfrica',
    name_en: 'South Africa',
    dial_code: '27',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ZAR',
  },
  {
    id: 'GS',
    name_es: 'Islas Georgia del Sur y Sandwich del Sur',
    name_en: 'South Georgia and South Sandwich Islands',
    dial_code: '500',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GBP',
  },
  {
    id: 'KR',
    name_es: 'Corea del Sur',
    name_en: 'South Korea',
    dial_code: '82',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'KRW',
  },
  {
    id: 'SS',
    name_es: 'Sudán del Sur',
    name_en: 'South Sudan',
    dial_code: '211',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SSP',
  },
  {
    id: 'ES',
    name_es: 'España',
    name_en: 'Spain',
    dial_code: '34',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'EUR',
  },
  {
    id: 'LK',
    name_es: 'Sri Lanka',
    name_en: 'Sri Lanka',
    dial_code: '94',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'LKR',
  },
  {
    id: 'SD',
    name_es: 'Sudán',
    name_en: 'Sudan',
    dial_code: '249',
    paypal_accepted: '0',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'SDG',
  },
  {
    id: 'SR',
    name_es: 'Surinam',
    name_en: 'Suriname',
    dial_code: '597',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SRD',
  },
  {
    id: 'SJ',
    name_es: 'Islas Svalbard y Jan Mayen',
    name_en: 'Svalbard and Jan Mayen Islands',
    dial_code: '47',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NOK',
  },
  {
    id: 'SZ',
    name_es: 'Swazilandia',
    name_en: 'Swaziland',
    dial_code: '268',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SZL',
  },
  {
    id: 'SE',
    name_es: 'Suecia',
    name_en: 'Sweden',
    dial_code: '46',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'SEK',
  },
  {
    id: 'CH',
    name_es: 'Suiza',
    name_en: 'Switzerland',
    dial_code: '41',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'CHF',
  },
  {
    id: 'SY',
    name_es: 'Siria',
    name_en: 'Syria',
    dial_code: '963',
    paypal_accepted: '0',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'SYP',
  },
  {
    id: 'TW',
    name_es: 'Taiwán',
    name_en: 'Taiwan',
    dial_code: '886',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'TWD',
  },
  {
    id: 'TJ',
    name_es: 'Tayikistán',
    name_en: 'Tajikistan',
    dial_code: '992',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'TJS',
  },
  {
    id: 'TZ',
    name_es: 'Tanzania',
    name_en: 'Tanzania',
    dial_code: '255',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'TZS',
  },
  {
    id: 'TH',
    name_es: 'Tailandia',
    name_en: 'Thailand',
    dial_code: '66',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'THB',
  },
  {
    id: 'TG',
    name_es: 'Togo',
    name_en: 'Togo',
    dial_code: '228',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XOF',
  },
  {
    id: 'TK',
    name_es: 'Tokelau',
    name_en: 'Tokelau',
    dial_code: '690',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'NZD',
  },
  {
    id: 'TO',
    name_es: 'Tonga',
    name_en: 'Tonga',
    dial_code: '676',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'TOP',
  },
  {
    id: 'TT',
    name_es: 'Trinidad y Tobago',
    name_en: 'Trinidad and Tobago',
    dial_code: '868',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'TTD',
  },
  {
    id: 'TN',
    name_es: 'Túnez',
    name_en: 'Tunisia',
    dial_code: '216',
    paypal_accepted: '1',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'TND',
  },
  {
    id: 'TR',
    name_es: 'Turquía',
    name_en: 'Turkey',
    dial_code: '90',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'TRY',
  },
  {
    id: 'TM',
    name_es: 'Turkmenistán',
    name_en: 'Turkmenistan',
    dial_code: '993',
    paypal_accepted: '1',
    cards_accepted: '0',
    locale_id: 'en',
    currency_id: 'TMT',
  },
  {
    id: 'TC',
    name_es: 'Islas Turcas y Caicos',
    name_en: 'Turks and Caicos Islands',
    dial_code: '1',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'TV',
    name_es: 'Tuvalu',
    name_en: 'Tuvalu',
    dial_code: '688',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AUD',
  },
  {
    id: 'UG',
    name_es: 'Uganda',
    name_en: 'Uganda',
    dial_code: '256',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'UGX',
  },
  {
    id: 'UA',
    name_es: 'Ucrania',
    name_en: 'Ukraine',
    dial_code: '380',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'UAH',
  },
  {
    id: 'AE',
    name_es: 'Emiratos Árabes Unidos',
    name_en: 'United Arab Emirates',
    dial_code: '971',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'AED',
  },
  {
    id: 'GB',
    name_es: 'Reino Unido',
    name_en: 'United Kingdom',
    dial_code: '44',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GBP',
  },
  {
    id: 'UM',
    name_es: 'Islas ultramarinas menores de Estados Unidos',
    name_en: 'United States Minor Outlying Islands',
    dial_code: '256',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'US',
    name_es: 'Estados Unidos de América',
    name_en: 'United States of America',
    dial_code: '1',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'UY',
    name_es: 'Uruguay',
    name_en: 'Uruguay',
    dial_code: '598',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'UYU',
  },
  {
    id: 'UZ',
    name_es: 'Uzbekistán',
    name_en: 'Uzbekistan',
    dial_code: '998',
    paypal_accepted: '0',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'UZS',
  },
  {
    id: 'VU',
    name_es: 'Vanuatu',
    name_en: 'Vanuatu',
    dial_code: '678',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'VUV',
  },
  {
    id: 'VA',
    name_es: 'Ciudad del Vaticano',
    name_en: 'Vatican City',
    dial_code: '379',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'EUR',
  },
  {
    id: 'VE',
    name_es: 'Venezuela',
    name_en: 'Venezuela',
    dial_code: '58',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'es',
    currency_id: 'VES',
  },
  {
    id: 'VN',
    name_es: 'Vietnam',
    name_en: 'Vietnam',
    dial_code: '84',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'VND',
  },
  {
    id: 'VG',
    name_es: 'Islas Vírgenes Británicas',
    name_en: 'Virgin Islands (British)',
    dial_code: '1284',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'VI',
    name_es: 'Islas Vírgenes (Estados Unidos)',
    name_en: 'Virgin Islands (United States)',
    dial_code: '1',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
  {
    id: 'GB-WLS',
    name_es: 'Gales',
    name_en: 'Wales',
    dial_code: '44',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'GBP',
  },
  {
    id: 'WF',
    name_es: 'Wallis y Futuna',
    name_en: 'Wallis and Futuna',
    dial_code: '681',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'XPF',
  },
  {
    id: 'YE',
    name_es: 'Yemen',
    name_en: 'Yemen',
    dial_code: '967',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'YER',
  },
  {
    id: 'ZM',
    name_es: 'Zambia',
    name_en: 'Zambia',
    dial_code: '260',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'ZMW',
  },
  {
    id: 'ZW',
    name_es: 'Zimbabue',
    name_en: 'Zimbabwe',
    dial_code: '263',
    paypal_accepted: '1',
    cards_accepted: '1',
    locale_id: 'en',
    currency_id: 'USD',
  },
];

module.exports = data;
